const ANSWERS = [
    { que: "hi", reply: "hey hello how are you..." },
    { que: "hello", reply: "Hi there! How can I help?" },
    { que: "how", reply: "How can I assist you today?" },
    { que: "resume", reply: "A resume is a document that outlines your work experience, skills, and education." },
    { que: "write", reply: "Start with your contact information, followed by a summary, work experience, education, and skills." },
    { que: "cover", reply: "A cover letter is a personalized letter that accompanies your resume, explaining your interest in the job." },
    { que: "prepare", reply: "Research the company, practice common interview questions, and prepare your own questions." },
    { que: "soft", reply: "Soft skills include communication, teamwork, problem-solving, and adaptability." },
    { que: "description", reply: "A job description outlines the responsibilities, qualifications, and skills needed for a specific position." },
    { que: "network", reply: "Attend events, connect on LinkedIn, and reach out to people in your field for informational interviews." },
    { que: "path", reply: "A career path is the progression of jobs and experiences that lead to a specific career goal." },
    { que: "choose", reply: "Consider your interests, skills, values, and the job market when choosing a career." },
    { que: "internship", reply: "An internship is a temporary position that provides practical experience in a specific field." },
    { que: "find", reply: "Look for internships on job boards, company websites, and through your school’s career center." },
    { que: "shadow", reply: "Job shadowing involves following a professional in your field of interest to learn about their day-to-day tasks." },
    { que: "negotiate", reply: "Research industry standards, know your worth, and practice your pitch before the conversation." },
    { que: "networking", reply: "A professional network consists of contacts you develop in your industry that can help with job opportunities." },
    { que: "thank", reply: "Thank the interviewer, express your appreciation, and reiterate your interest in the position." },
    { que: "performance", reply: "A performance review is an evaluation of an employee's job performance over a specific period." },
    { que: "conflict", reply: "Address the issue directly with the person involved and seek a solution through open communication." },
    { que: "advancement", reply: "Career advancement refers to the process of progressing to higher-level positions within your career." },
    { que: "goals", reply: "Define specific, measurable, achievable, relevant, and time-bound (SMART) goals for your career." },
    { que: "transferable", reply: "Transferable skills are abilities that can be applied across different jobs and industries." },
    { que: "LinkedIn", reply: "Ensure your profile is complete, includes a professional photo, and highlights your skills and achievements." },
    { que: "coach", reply: "A career coach is a professional who helps individuals develop their careers and achieve their goals." },
    { que: "strong", reply: "Tailor your resume for each job application, focusing on relevant experience and quantifiable achievements." },
    { que: "fair", reply: "A job fair is an event where employers and job seekers meet to discuss job opportunities." },
    { que: "phone", reply: "Prepare your answers, find a quiet space, and have your resume handy during the call." },
    { que: "remote", reply: "Remote work allows employees to work from a location outside of the traditional office, often from home." },
    { que: "succeed", reply: "Stay organized, communicate regularly with your team, and set a dedicated workspace." },
    { que: "mentorship", reply: "A mentorship is a relationship where a more experienced professional guides someone less experienced." },
    { que: "find", reply: "Look for someone in your industry you admire, and reach out to them with a clear ask for guidance." },
    { que: "hard", reply: "Hard skills are specific, teachable abilities or knowledge sets, such as programming or accounting." },
    { que: "public", reply: "Practice regularly, seek feedback, and consider joining groups like Toastmasters." },
    { que: "change", reply: "A career change involves moving from one profession or industry to another." },
    { que: "transition", reply: "Assess your skills, research the new field, and consider additional training or education." },
    { que: "application", reply: "A job application is a formal request for employment that typically includes your resume and cover letter." },
    { que: "assessment", reply: "Review the skills listed in the job description and practice relevant tasks or tests." },
    { que: "pitch", reply: "An elevator pitch is a brief, persuasive speech that you can use to spark interest in what you do." },
    { que: "management", reply: "Prioritize tasks, set deadlines, and use tools like calendars or to-do lists." },
    { que: "portfolio", reply: "A portfolio is a collection of work samples that showcase your skills and achievements." },
    { que: "reference", reply: "Choose someone who knows your work well and ask them politely, explaining the context." },
    { que: "diversity", reply: "Workplace diversity refers to the inclusion of individuals from different backgrounds, cultures, and perspectives." },
    { que: "environment", reply: "Encourage open communication, recognize achievements, and promote teamwork." },
    { que: "intelligence", reply: "Emotional intelligence is the ability to understand and manage your own emotions and those of others." },
    { que: "brand", reply: "Define your unique value, create an online presence, and network within your industry." },
    { que: "feedback", reply: "Feedback helps you improve your performance and grow in your career." },
    { que: "balance", reply: "Set boundaries, prioritize self-care, and manage your time effectively." },
    { que: "entry", reply: "An entry-level job is a position suitable for those new to a field, often requiring minimal experience." },
    { que: "excel", reply: "Be proactive, seek feedback, and continuously learn from your colleagues." },
    { que: "benefits", reply: "Job benefits are non-wage compensations provided to employees, such as health insurance and retirement plans." },
    { que: "rejection", reply: "Reflect on the experience, seek feedback, and use it as a learning opportunity for future applications." },
    { que: "hustle", reply: "A side hustle is a secondary job or business that you do in addition to your main job." },
    { que: "work-life", reply: "Set clear boundaries between work and personal time, and prioritize tasks effectively." },
    { que: "gig", reply: "The gig economy is a labor market characterized by short-term, flexible jobs instead of permanent positions." },
    { que: "adapt", reply: "Be open-minded, ask questions, and seek to build relationships with your new colleagues." },
    { que: "development", reply: "Professional development involves training and education to enhance your skills and career prospects." },
    { que: "motivation", reply: "Set personal goals, seek new challenges, and find meaning in your work." },
    { que: "skills", reply: "Skills are the abilities you acquire through training or experience that help you perform your job." },
    { que: "interview", reply: "An interview is a conversation between a job seeker and an employer to assess fit for a position." },
    { que: "follow-up", reply: "A follow-up is a message sent after an interview to thank the interviewer and express continued interest." },
    { que: "salary", reply: "Salary is the compensation paid to an employee for their work, typically expressed as an annual amount." },
    { que: "workplace", reply: "The workplace is the physical or virtual environment where employees perform their jobs." },
    { que: "productivity", reply: "Productivity refers to the efficiency of work performed in a given time." },
    { que: "stress", reply: "Work-related stress can arise from high demands, tight deadlines, or lack of support." },
    { que: "governance", reply: "Workplace governance involves policies and procedures that guide behavior and decision-making." },
    { que: "leadership", reply: "Leadership is the ability to guide and motivate a team toward achieving common goals." },
    { que: "evaluation", reply: "Evaluation is the process of assessing an employee's performance and contributions to the organization." },
    { que: "coaching", reply: "Coaching involves providing guidance and support to help someone improve their skills and performance." },
    { que: "training", reply: "Training programs enhance employees' skills and knowledge for their current or future roles." },
    { que: "culture", reply: "Workplace culture refers to the shared values, beliefs, and behaviors within an organization." },
    { que: "collaboration", reply: "Collaboration is the act of working together to achieve a common goal." },
    { que: "flexibility", reply: "Job flexibility allows employees to adapt their work schedules and locations." },
    { que: "recruitment", reply: "Recruitment is the process of finding and attracting candidates for job openings." },
    { que: "onboarding", reply: "Onboarding is the process of integrating new employees into the organization." },
    { que: "performance", reply: "Performance metrics help evaluate how well employees meet their job expectations." },
    { que: "retention", reply: "Employee retention strategies aim to keep talented employees within an organization." },
    { que: "recognition", reply: "Employee recognition involves acknowledging and rewarding employees for their contributions." },
];

export { ANSWERS };
